# Generated by Django 6.0.2 on 2026-02-15 06:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='图标')),
                ('category', models.CharField(choices=[('origin', '产地'), ('variety', '品种'), ('process', '处理法'), ('count', '数量'), ('special', '特殊')], max_length=20, verbose_name='类别')),
                ('rarity', models.CharField(choices=[('common', '普通'), ('rare', '稀有'), ('epic', '史诗'), ('legendary', '传说')], default='common', max_length=20, verbose_name='稀有度')),
                ('condition', models.JSONField(default=dict, verbose_name='解锁条件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'ordering': ['category', 'rarity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='豆名')),
                ('region', models.CharField(max_length=100, verbose_name='产区')),
                ('variety', models.CharField(max_length=100, verbose_name='品种')),
                ('process', models.CharField(choices=[('washed', '水洗'), ('natural', '日晒'), ('honey', '蜜处理'), ('wet_hulled', '湿刨法'), ('anaerobic', '厌氧发酵'), ('carbonic', '二氧化碳浸渍'), ('lactic', '乳酸发酵'), ('monsoon', '季风处理'), ('other', '其他')], max_length=20, verbose_name='处理法')),
                ('altitude_min', models.IntegerField(blank=True, null=True, verbose_name='最低海拔')),
                ('altitude_max', models.IntegerField(blank=True, null=True, verbose_name='最高海拔')),
                ('flavor_notes', models.JSONField(default=list, verbose_name='风味标签')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('brewing_methods', models.JSONField(default=list, verbose_name='推荐冲煮方式')),
                ('grind_size', models.CharField(blank=True, max_length=50, verbose_name='研磨度')),
                ('ratio', models.CharField(blank=True, max_length=20, verbose_name='粉水比')),
                ('temperature', models.CharField(blank=True, max_length=20, verbose_name='水温')),
                ('brew_time', models.CharField(blank=True, max_length=50, verbose_name='冲煮时间')),
                ('data_source', models.CharField(blank=True, max_length=200, verbose_name='数据来源')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '咖啡豆',
                'verbose_name_plural': '咖啡豆',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产地名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='国家代码')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('description', models.TextField(verbose_name='产地描述')),
                ('history', models.TextField(blank=True, verbose_name='发展历程')),
                ('industry_status', models.TextField(blank=True, verbose_name='产业现状')),
                ('flavor_profile', models.TextField(blank=True, verbose_name='风味特征')),
                ('image_url', models.URLField(blank=True, verbose_name='图片URL')),
                ('video_url', models.URLField(blank=True, verbose_name='视频URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产地',
                'verbose_name_plural': '产地',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OCRCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=64, unique=True, verbose_name='图片哈希')),
                ('recognized_text', models.TextField(verbose_name='识别文本')),
                ('confidence', models.FloatField(default=0, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('matched_coffee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coffeebean', verbose_name='匹配的咖啡')),
            ],
            options={
                'verbose_name': 'OCR缓存',
                'verbose_name_plural': 'OCR缓存',
            },
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_beans', to='api.origin', verbose_name='产地'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='records/%Y/%m/', verbose_name='照片')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('notes', models.TextField(blank=True, verbose_name='笔记')),
                ('brewing_method', models.CharField(blank=True, max_length=50, verbose_name='冲煮方式')),
                ('brewing_params', models.JSONField(blank=True, default=dict, verbose_name='冲煮参数')),
                ('checkin_type', models.CharField(choices=[('brew', '冲煮打卡'), ('taste', '品鉴记录'), ('purchase', '购买记录'), ('wishlist', '想喝清单')], default='brew', max_length=20, verbose_name='打卡类型')),
                ('recognized_by_ocr', models.BooleanField(default=False, verbose_name='OCR识别')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='OCR置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coffee_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='api.coffeebean', verbose_name='咖啡豆')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户记录',
                'verbose_name_plural': '用户记录',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'coffee_bean')},
            },
        ),
    ]
