# Generated by Django 5.2.11 on 2026-02-15 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='acidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='酸度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='aftertaste',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='余韵'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='balance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='平衡度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='bitterness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='苦度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='bloom_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='闷蒸时间(秒)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='body',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='醇厚度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='coffee_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='咖啡粉量(g)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='extraction_yield',
            field=models.FloatField(blank=True, null=True, verbose_name='萃取率(%)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='flavor_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='风味标签'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='grind_setting',
            field=models.CharField(blank=True, max_length=20, verbose_name='研磨刻度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='grind_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='研磨度描述'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='ratio',
            field=models.CharField(blank=True, max_length=20, verbose_name='粉水比'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='sweetness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='甜度'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='tds',
            field=models.FloatField(blank=True, null=True, verbose_name='TDS浓度(ppm)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='总萃取时间(秒)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='water_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='水温(°C)'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='water_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='水质'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='water_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='注水量(g)'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='brewing_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='其他冲煮参数'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='总体评分'),
        ),
        migrations.CreateModel(
            name='UserCoffeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购买价格(元)')),
                ('purchase_weight', models.FloatField(verbose_name='购买重量(g)')),
                ('remaining_weight', models.FloatField(verbose_name='剩余重量(g)')),
                ('roast_date', models.DateField(blank=True, null=True, verbose_name='烘焙日期')),
                ('best_before_date', models.DateField(blank=True, null=True, verbose_name='最佳赏味期至')),
                ('status', models.CharField(choices=[('unopened', '未开封'), ('opened', '已开封'), ('finished', '已喝完'), ('discarded', '已丢弃')], default='unopened', max_length=20, verbose_name='状态')),
                ('storage_method', models.CharField(blank=True, max_length=100, verbose_name='存储方式')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coffee_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='api.coffeebean', verbose_name='咖啡豆')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_inventory', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '咖啡豆库存',
                'verbose_name_plural': '咖啡豆库存',
                'ordering': ['-created_at'],
            },
        ),
    ]
